-- MySQL Script generated by MySQL Workbench
-- Mon Oct 12 18:27:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gestor_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gestor_db` ;

-- -----------------------------------------------------
-- Schema gestor_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestor_db` DEFAULT CHARACTER SET utf8 ;
USE `gestor_db` ;

-- -----------------------------------------------------
-- Table `gestor_db`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_db`.`usuario` ;

CREATE TABLE IF NOT EXISTS `gestor_db`.`usuario` (
  `id` INT(4) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `nick` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_db`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_db`.`rol` ;

CREATE TABLE IF NOT EXISTS `gestor_db`.`rol` (
  `id` INT(4) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_db`.`usuario_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_db`.`usuario_rol` ;

CREATE TABLE IF NOT EXISTS `gestor_db`.`usuario_rol` (
  `usuario` INT(4) NOT NULL,
  `rol` INT(4) NOT NULL,
  PRIMARY KEY (`usuario`, `rol`),
  INDEX `fk_usuario_rol_rol_idx` (`rol` ASC),
  INDEX `fk_usuario_rol_usuario_idx` (`usuario` ASC),
  CONSTRAINT `fk_usuario_has_rol_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `gestor_db`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_rol_rol1`
    FOREIGN KEY (`rol`)
    REFERENCES `gestor_db`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_db`.`carpeta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_db`.`carpeta` ;

CREATE TABLE IF NOT EXISTS `gestor_db`.`carpeta` (
  `id` INT(4) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `usuario` INT(4) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_carpeta_usuario_idx` (`usuario` ASC),
  CONSTRAINT `fk_carpeta_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `gestor_db`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_db`.`documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_db`.`documento` ;

CREATE TABLE IF NOT EXISTS `gestor_db`.`documento` (
  `id` INT(4) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `fecha_create` DATE NOT NULL,
  `fecha_edit` DATE NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  `size` INT(20) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `archivo` LONGBLOB NOT NULL,
  `carpeta` INT(4) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_documento_carpeta_idx` (`carpeta` ASC),
  CONSTRAINT `fk_documento_carpeta1`
    FOREIGN KEY (`carpeta`)
    REFERENCES `gestor_db`.`carpeta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_db`.`auditoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_db`.`auditoria` ;

CREATE TABLE IF NOT EXISTS `gestor_db`.`auditoria` (
  `id` INT(4) NOT NULL,
  `fecha` DATE NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `usuario` INT(4) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_auditoria_usuario_idx` (`usuario` ASC),
  CONSTRAINT `fk_auditoria_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `gestor_db`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
